### PR TITLE
Adds scale bar, range tool, and subplot sections (CZI-related updates)

### PR DESCRIPTION
**Pull request by droumis**
Added scale bar, range tool, and subplot sections where I thought they fit best. 

I'm happy for any of the core team to directly edit/contribute to this, and merge at their discretion.

### CODE REVIEW

**Comment by tcmetzger** [comment]
These are some great additions, thank you!

For the Subplot section in chapter 9: The example here introduces a JS Callback and Switch widget, all of which are really only introduced in chapter 11. How about we remove the switch and callback from this example here and instead add a "🔁" interactivity section? There are several examples of this throughout the notebooks where we basically ask users to make small changes to the code and rerun the cell to see the effect (the section "How do I use this tutorial?" in 01_introduction.ipynb introduces this concept). In this case, we could ask users to change the level parameter themselves, e.g.:

`level = 1  # 🔁 Try changing the level parameter to 0`

What do you think?

**Comment by droumis** [comment]
> What do you think?

makes sense to me

**Comment by bryevdv** [comment]
@droumis will you be able to make those changes?

**Comment by droumis** [comment]
I think this is ready for a final review

**Comment by bryevdv** [comment]
Thanks @droumis !

**Pull request merged**
