### PR TITLE
Remove black format pre-commit

### PR DESCRIPTION
**Pull request by bryevdv**
cc @ianthomas23 @pavithraes @tcmetzger 

Submitted for consideration. I am dubious of `black` formatting in general these days, and especially in notebooks. But I think as @ianthomas23 has pointed out we should not sacrifice accepted mathematical notation just to appease a formatter.

### CODE REVIEW

**Comment by tcmetzger** [comment]
Sure, we can remove black! I had added it mostly as a way to force myself to use a consistent style 😅

**Comment by tcmetzger** [comment]
For consistency, I'd still generally recommend using black code style where it makes sense. I have updated the readme to reflect that!

**Comment by tcmetzger** [comment]
@ianthomas23 Now that we have removed black, would you like to update your example back to your preferred format (https://github.com/bokeh/tutorial/pull/5#issuecomment-1604160242)?

**Comment by ianthomas23** [comment]
Thanks, I have done this in #15.

**Pull request merged**
